/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.grp9.risk.server;
import java.io.ObjectOutputStream;
import java.io.OutputStream;

import java.net.Socket;
import edu.duke.ece651.grp9.risk.shared.Map;
//import edu.duke.ece651.grp9.risk.shared.MapPackage;

public class App {
    public static void main(String[] args) {
      Map myMap = new Map();
      myMap.buildTestMap();
      try{ 
        Socket socket=new Socket("localhost", 6666);
        OutputStream outputStream = socket.getOutputStream();
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(outputStream);
        objectOutputStream.writeObject(myMap);
        socket.close();
        }catch(Exception e){System.out.println(e);
      }
    }
}
