/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.grp9.risk.client;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Iterator;

import edu.duke.ece651.grp9.risk.shared.Map;
import edu.duke.ece651.grp9.risk.shared.Territory;

public class App {
    public static void main(String[] args) {

     try{
       
       //receive map from client
       ServerSocket ss = new ServerSocket(6666);
       Socket socket = ss.accept();
       InputStream inputStream = socket.getInputStream();
       ObjectInputStream objectInputStream = new ObjectInputStream(inputStream);
       
       Map myMap = (Map)objectInputStream.readObject();
       System.out.println("Receive Map form server:");
       Iterator<Territory> it = myMap.getList().iterator();
       while (it.hasNext()){
         System.out.println(it.next().getName());
       }
       ss.close();
       socket.close();
    }catch(Exception e){System.out.println(e);}
    }

}
